export interface PokemonInput {
    row: string,
    name: string,
    pokedex_number: number,
    img_name: number,
    generation: number,
    evolution_stage: number,
    evolved: number,
    familyID: number,
    cross_gen: number,
    type_1: string,
    type_2: string,
    weather_1: string,
    weather_2: string,
    stat_total: number,
    atk: number,
    def: number,
    sta: number,
    legendary: number,
    aquireable: number,
    spawns: number,	
    regional: number,	
    raidable: number,
    hatchable: number,
    shiny: number,
    nest: number,
    pokemon_new: number,
    not_gettable: number,
    future_evolve: number,
    combat_power_100_40: number,
    combat_power_100_39: number
}

